package com.example.booking;

public enum Booker {
    APARTMENT_1,
    APARTMENT_2,
    APARTMENT_3,
    APARTMENT_4,
    APARTMENT_5,
    APARTMENT_6,
    APARTMENT_7,
    APARTMENT_9,
    APARTMENT_10,
    APARTMENT_11,
    APARTMENT_12,
    APARTMENT_13,
    APARTMENT_14,
    APARTMENT_15,
    APARTMENT_16,
    APARTMENT_17,
    APARTMENT_18,
    APARTMENT_19,
    APARTMENT_20;
}
